name: Deploy to Local Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Atualizar Repositorio e Reconstruir Conteineres
        run: |
          cd /data/repositorio-aprendeti/
          git fetch origin main
          git reset --hard origin/main
          docker compose up -d --build
